apiVersion: v1
kind: Service
metadata:
  name: dev-ops-app-mysql
spec:
  selector:
    app: dev-ops-app-mysql
    release: initial-release
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306